export async function obterCidades() {
  // const res = await fetch(`https://servicodados.ibge.gov.br/api/v1/localidades/estados/MS/municipios`)
  // const data = await res.json()

  // if (!data) {
  //   return { notFound: true }
  // }
  const data = ["Campo Grande",
    "Dourados",
    "Três Lagoas",
    "Corumbá",
    "Ponta Porã",
    "Sidrolândia",
    "Naviraí",
    "Nova Andradina",
    "Maracaju",
    "Aquidauana",
    "Paranaíba",
    "Amambai",
    "Rio Brilhante",
    "Coxim",
    "Caarapó",
    "Miranda",
    "São Gabriel do Oeste",
    "Jardim",
    "Aparecida do Taboado",
    "Chapadão do Sul",
    "Anastácio",
    "Itaporã",
    "Ribas do Rio Pardo",
    "Bela Vista",
    "Ladário",
    "Bataguassu",
    "Ivinhema",
    "Nova Alvorada do Sul",
    "Terenos",
    "Bonito",
    "Cassilândia",
    "Itaquiraí",
    "Costa Rica",
    "Rio Verde de Mato Grosso",
    "Sonora",
    "Fátima do Sul",
    "Mundo Novo",
    "Porto Murtinho",
    "Iguatemi",
    "Água Clara",
    "Coronel Sapucaia",
    "Paranhos",
    "Nioaque",
    "Camapuã",
    "Deodápolis",
    "Eldorado",
    "Aral Moreira",
    "Brasilândia",
    "Tacuru",
    "Dois Irmãos do Buriti",
    "Batayporã",
    "Angélica",
    "Sete Quedas",
    "Glória de Dourados",
    "Guia Lopes da Laguna",
    "Japorã",
    "Anaurilândia",
    "Antônio João",
    "Santa Rita do Pardo",
    "Bodoquena",
    "Pedro Gomes",
    "Inocência",
    "Laguna Carapã",
    "Bandeirantes",
    "Jaraguari",
    "Juti",
    "Selvíria",
    "Caracol",
    "Vicentina",
    "Corguinho",
    "Douradina",
    "Paraíso das Águas",
    "Alcinópolis",
    "Rochedo",
    "Rio Negro",
    "Jateí",
    "Novo Horizonte do Sul",
    "Taquarussu",
    "Figueirão"]

  return data
}
